#!/usr/bin/env bash

if [[ $1 == "-h" ]]
then
    echo -e "Usage: \n  type 1: git_mirror 1 [source] [dir_source] [destination] [dir_destination]"
    echo -e "  type 2: git_mirror 2 [destination] [dir_destination]"
    exit 0
fi

if [[ $1 == 1 ]]
then
    echo "Cloning repository"
    git clone $2 $3
    cd $3
    echo "Creating Mirror"
    git push --mirror $4
    cd ..
    echo "Cloning mirror"
    git clone $4 $5
else 
    echo "Creating Mirror"
    git push --mirror $2
    cd ..
    echo "Cloning mirror"
    git clone $2 $3
fi