#!/usr/bin/bash

echo "===Config==="
git config --global --add safe.directory $PWD
echo "===git Add==="
STATUS=($(git status -s))
COMMIT=""
for (( c=0; c<${#STATUS[@]}; c+=2 ))
do
    
    if [[ ${STATUS[$c]} = "??" || ${STATUS[$c]} = *"M"* ||  ${STATUS[$c]} = *"C"* ||  ${STATUS[$c]} = *"T"* || ${STATUS[$c]} = *"A"* || ${STATUS[$c]} = *"D"* || ${STATUS[$c]} = *"R"* || ${STATUS[$c]} = *"U"* ]]
    then
        git add ${STATUS[$c + 1]}
        if [[ ${STATUS[$c]} = "??" || ${STATUS[$c]} = *"A"* ]]
        then
            TMP="[ADD]"
        elif [[ ${STATUS[$c]} == *"M"* ]]
        then
            TMP="[MOD]"
        elif [[ ${STATUS[$c]} = *"C"* ]]
        then
            TMP="[COPY]"
        elif [[ ${STATUS[$c]} = *"T"* ]]
        then
            TMP="[CHANGED]"
        elif [[ ${STATUS[$c]} = *"D"* ]]
        then
            TMP="[DELETE]"
        else
            TMP="[UPDATED]"
        fi
        COMMIT+=$TMP" "${STATUS[$c + 1]}", "
    fi
done
echo "===Commiting==="
git commit -m "$COMMIT" -m $'$1'
echo "===Pushing==="
git push